### ISSUE TITLE
Resume Development

### ISSUE THREAD

**Issue by ZayneLee** [ZayneLee/kotlin-portfolio#28]
## Description
Resume Development

## To-Do
- [x] fragment-card-experience.html
- [x] fragment-list-skill.html
- [x] fragment-card-achievement.html

## ETC
